name: Publish

on:
  pull_request:
    branches: [ master ]
    types:
      - closed
jobs:
  publish:
    if: github.event.pull_request.merged == true
    uses: kne-union/actions/.github/workflows/publish-content-workflow.yml@master
    secrets: inherit
    with:
      publish-to-npm: true
